/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./views/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./App.tsx",
  ],
  theme: {
    extend: {
      colors: {
        // App Background & Surface Grays -> Home Assistant Backgrounds & Texts
        'cool-gray': {
          950: 'var(--ha-bg-app)',
          900: 'var(--ha-bg-card)',
          850: 'var(--ha-bg-surface)',
          800: 'var(--ha-bg-input)',
          750: 'var(--ha-divider)',
          700: 'var(--ha-border)',
          650: 'var(--ha-bg-chip)',
          600: 'var(--ha-bg-chip)',
          550: 'var(--ha-text-muted)',
          500: 'var(--ha-text-muted)',
          455: 'var(--ha-text-secondary)',
          400: 'var(--ha-text-secondary)',
          300: 'var(--ha-text-secondary)',
          200: 'var(--ha-text-primary)',
          100: 'var(--ha-text-primary)',
          50:  'var(--ha-text-primary)',
        },
        slate: {
          950: 'var(--ha-bg-app)',
          900: 'var(--ha-bg-card)',
          800: 'var(--ha-bg-surface)',
          700: 'var(--ha-bg-input)',
          600: 'var(--ha-bg-chip)',
          500: 'var(--ha-text-muted)',
          400: 'var(--ha-text-secondary)',
          300: 'var(--ha-text-secondary)',
          200: 'var(--ha-text-primary)',
          100: 'var(--ha-text-primary)',
          50:  'var(--ha-text-primary)',
        },
        zinc: {
          950: 'var(--ha-bg-app)',
          900: 'var(--ha-bg-card)',
          800: 'var(--ha-bg-surface)',
          700: 'var(--ha-bg-input)',
          600: 'var(--ha-bg-chip)',
          500: 'var(--ha-text-muted)',
          400: 'var(--ha-text-secondary)',
          300: 'var(--ha-text-secondary)',
          200: 'var(--ha-text-primary)',
          100: 'var(--ha-text-primary)',
          50:  'var(--ha-text-primary)',
        },
        gray: {
          950: 'var(--ha-bg-app)',
          900: 'var(--ha-bg-card)',
          800: 'var(--ha-bg-surface)',
          700: 'var(--ha-bg-input)',
          600: 'var(--ha-bg-chip)',
          500: 'var(--ha-text-muted)',
          400: 'var(--ha-text-secondary)',
          300: 'var(--ha-text-secondary)',
          200: 'var(--ha-text-primary)',
          100: 'var(--ha-text-primary)',
          50:  'var(--ha-text-primary)',
        },
        neutral: {
          950: 'var(--ha-bg-app)',
          900: 'var(--ha-bg-card)',
          800: 'var(--ha-bg-surface)',
          700: 'var(--ha-bg-input)',
          600: 'var(--ha-bg-chip)',
          500: 'var(--ha-text-muted)',
          400: 'var(--ha-text-secondary)',
          300: 'var(--ha-text-secondary)',
          200: 'var(--ha-text-primary)',
          100: 'var(--ha-text-primary)',
          50:  'var(--ha-text-primary)',
        },

        // Primary Accents (Cyan, Blue, Indigo, Sky, Teal) -> HA Primary / Dark Primary / Light Primary
        cyan: {
          50:  'var(--ha-light-primary-color)',
          100: 'var(--ha-light-primary-color)',
          200: 'var(--ha-light-primary-color)',
          300: 'var(--ha-light-primary-color)',
          400: 'var(--ha-primary-color)',
          500: 'var(--ha-primary-color)',
          600: 'var(--ha-dark-primary-color)',
          700: 'var(--ha-dark-primary-color)',
          800: 'var(--ha-dark-primary-color)',
          900: 'var(--ha-bg-chip)',
          950: 'var(--ha-bg-surface)',
        },
        blue: {
          50:  'var(--ha-light-primary-color)',
          100: 'var(--ha-light-primary-color)',
          200: 'var(--ha-light-primary-color)',
          300: 'var(--ha-light-primary-color)',
          400: 'var(--ha-primary-color)',
          500: 'var(--ha-primary-color)',
          600: 'var(--ha-dark-primary-color)',
          700: 'var(--ha-dark-primary-color)',
          800: 'var(--ha-dark-primary-color)',
          900: 'var(--ha-bg-chip)',
          950: 'var(--ha-bg-surface)',
        },
        indigo: {
          50:  'var(--ha-light-primary-color)',
          100: 'var(--ha-light-primary-color)',
          200: 'var(--ha-light-primary-color)',
          300: 'var(--ha-light-primary-color)',
          400: 'var(--ha-primary-color)',
          500: 'var(--ha-primary-color)',
          600: 'var(--ha-dark-primary-color)',
          700: 'var(--ha-dark-primary-color)',
          800: 'var(--ha-dark-primary-color)',
          900: 'var(--ha-bg-chip)',
          950: 'var(--ha-bg-surface)',
        },

        // Amber & Warning -> HA Accent & Warning Colors
        amber: {
          50:  'var(--ha-accent-color)',
          100: 'var(--ha-accent-color)',
          200: 'var(--ha-accent-color)',
          300: 'var(--ha-accent-color)',
          400: 'var(--ha-warning-color)',
          500: 'var(--ha-warning-color)',
          600: 'var(--ha-warning-color)',
          700: 'var(--ha-warning-color)',
          800: 'var(--ha-warning-color)',
          900: 'var(--ha-bg-chip)',
          950: 'var(--ha-bg-surface)',
        },
        yellow: {
          50:  'var(--ha-accent-color)',
          100: 'var(--ha-accent-color)',
          200: 'var(--ha-accent-color)',
          300: 'var(--ha-accent-color)',
          400: 'var(--ha-warning-color)',
          500: 'var(--ha-warning-color)',
          600: 'var(--ha-warning-color)',
          700: 'var(--ha-warning-color)',
          800: 'var(--ha-warning-color)',
          900: 'var(--ha-bg-chip)',
          950: 'var(--ha-bg-surface)',
        },

        // Emerald & Success -> HA Success Color
        emerald: {
          50:  'var(--ha-success-color)',
          100: 'var(--ha-success-color)',
          200: 'var(--ha-success-color)',
          300: 'var(--ha-success-color)',
          400: 'var(--ha-success-color)',
          500: 'var(--ha-success-color)',
          600: 'var(--ha-success-color)',
          700: 'var(--ha-success-color)',
          800: 'var(--ha-success-color)',
          900: 'var(--ha-bg-chip)',
          950: 'var(--ha-bg-surface)',
        },
        green: {
          50:  'var(--ha-success-color)',
          100: 'var(--ha-success-color)',
          200: 'var(--ha-success-color)',
          300: 'var(--ha-success-color)',
          400: 'var(--ha-success-color)',
          500: 'var(--ha-success-color)',
          600: 'var(--ha-success-color)',
          700: 'var(--ha-success-color)',
          800: 'var(--ha-success-color)',
          900: 'var(--ha-bg-chip)',
          950: 'var(--ha-bg-surface)',
        },

        // Red & Danger -> HA Error Color
        red: {
          50:  'var(--ha-error-color)',
          100: 'var(--ha-error-color)',
          200: 'var(--ha-error-color)',
          300: 'var(--ha-error-color)',
          400: 'var(--ha-error-color)',
          500: 'var(--ha-error-color)',
          600: 'var(--ha-error-color)',
          700: 'var(--ha-error-color)',
          800: 'var(--ha-error-color)',
          900: 'var(--ha-bg-chip)',
          950: 'var(--ha-bg-surface)',
        },
        rose: {
          50:  'var(--ha-error-color)',
          100: 'var(--ha-error-color)',
          200: 'var(--ha-error-color)',
          300: 'var(--ha-error-color)',
          400: 'var(--ha-error-color)',
          500: 'var(--ha-error-color)',
          600: 'var(--ha-error-color)',
          700: 'var(--ha-error-color)',
          800: 'var(--ha-error-color)',
          900: 'var(--ha-bg-chip)',
          950: 'var(--ha-bg-surface)',
        },
      },
    },
  },
  plugins: [],
};
